name: Continuous Integration

on:
  push:
    branches:
      - feature/ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN  }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker build -t ramesh144/talento-nodejs:latest .
        docker build -t ramesh144/talento-nodejs:$(git rev-parse --short HEAD) .
        docker push ramesh144/talento-nodejs:latest
        docker push ramesh144/talento-nodejs:$(git rev-parse --short HEAD)
        docker logout
